name: Multiverse Simulation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Cancel if stuck
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Multiverse Simulation
      run: |
        # Install dependencies (if any) and run with timeout
        go run . &
        SIM_PID=$!
        sleep 30
        kill $SIM_PID